### ISSUE TITLE
Error when saving any file: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by awaer** [kimroen/ember-cli-autoprefixer#25]
Ember: v2.1.0
Ember CLI: v1.13.8

There are no problems starting `ember serve`, but a build error is triggered when any files are saved. 

This issue began sometime in the last week and appears to be connected to the release of broccoli-autoprefixer v4.1.0. The issue is resolved if I edit this addon's package.json to force broccoli-autoprefixer v4.0.0, though I'm unsure if the issue lies here or there. 

```javascript
ENOENT, no such file or directory '/Projects/Thing/ember/tmp/autoprefixer_filter-output_path-NncgYwdM.tmp/assets/old-ie.js'
Error: ENOENT, no such file or directory '/Projects/Thing/ember/tmp/autoprefixer_filter-output_path-NncgYwdM.tmp/assets/old-ie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:13:21)
    at copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at Function.copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at /Projects/Thing/ember/node_modules/ember-cli/lib/models/builder.js:103:19
    at lib$rsvp$$internal$$initializePromise (/Projects/Thing/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:541:9)
    at PromiseExt.lib$rsvp$promise$$Promise [as _superConstructor] (/Projects/Thing/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:757:9)
    at new PromiseExt (/Projects/Thing/ember/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.copyToOutputPath (/Projects/Thing/ember/node_modules/ember-cli/lib/models/builder.js:98:12)
```

**Comment by kimroen** [comment]
Hi! Like you are guessing, all of this is handled within `broccoli-autoprefixer`, so there is almost certainly something going on there. [The diff between the versions](https://github.com/sindresorhus/broccoli-autoprefixer/compare/v4.0.0...v4.1.0) shows that the only change was using `broccoli-persistent-filter` instead of `broccoli-filter`, so we can assume the error lies there: https://github.com/stefanpenner/broccoli-persistent-filter

**Comment by awaer** [comment]
Ok, thanks @kimroen. I'll open an issue over there.
